config/routes.rb
Customagic::Application.routes.draw do

  # Admin Routes
  constraints RouteConstraints::Subdomain::Admin do
    devise_for :admin, path: "", module: "admin",
      path_names: { sign_in: :login, sign_out: :logout },
      only: [:sessions, :passwords, :unlock]

    as :admin do
      get   "login"   => "admin/sessions#new",     as: :admin_login
      post  "login"   => "admin/sessions#create",  as: :admin_session
      get   "logout"  => "admin/sessions#destroy", as: :admin_logout

      resource :password, controller: "admin/passwords"
    end

    scope module: "admin" do
      resources :mastheads
      resources :shops
      resources :orders
      resources :users
      resources :products do
        get :toggle_feature
        get :toggle_visibility
        get :update_category
      end
      resources :themes
      resources :admins
    end

    match 'login_as/:user_id' => 'admin/user_sessions#create', as: :login_as
    match 'search' => 'admin/search#index'

    match "sites-validate" => "sites#validate"
    match "users-validate" => "user#validate"

    root to: "admin/dashboard#index"

  end

  resource :marketplace do
    get :featured
    get :fresh
  end
  resources :canned_images do 
    get :memes, on: :collection
  end
  resources :shops do
    get  :successful_purchase
    get  :cancelled_purchase
    resources :assets do
      post :create_photo, on: :collection
    end
    resources :customers
    resources :earnings
    resources :products do
      get  :edit_info,    on: :member
      post :update_info,  on: :member
      get  :ready,        on: :member
    end
  end

  resources :products
  
  resources :carts do
    get 'view',           on: :collection
    get 'check_out',      on: :collection
    get 'empty',          on: :collection
    get 'update_cart',    on: :collection
    get 'add_product',    on: :collection
    get 'remove_product', on: :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in',  :to => 'devise/sessions#new',     :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users

  match '/orders' => "orders#create", :method => :post
  match '/shop/successful_purchase' => 'shops#successful_purchase', :method => :get
  match '/shop/cancelled_purchase'  => 'shops#cancelled_purchase',  :method => :get
  match "/payment_notifications/paypal" => "payment_notifications#paypal", :as => :paypal_payment_notifications
  # match "/:shop_id/:id" => "products#show", :method => :get
  match "/:shop_id/products/new" => "products#new", :method => :get
  match "/:shop_id/products/:id/edit" => "products#edit", :method => :get
  match "/:shop_id/products/:id/edit_info" => "products#edit_info", :method => :get
  match "/user/hearts" => "users#hearts"
  match "/user/toggle_heart/:id" => "users#toggle_heart"
  match "/:id" => "shops#show", :method => :get

  root :to => "landing#index"

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  layout false

  respond_to :js, :html, :json

  def index

    @date_today = DateTime.now.in_time_zone(current_partner.time_zone || "GMT")

    unless is_infinitely_admin?
      
      @partner_accounts ||= Account.where(:partner => @current_partner_name).map(&:_id)
      @sites = Site.where(:partner => @current_partner_name)

      @latest_sites ||= @sites.desc(:created_at).limit(50)
      @unclaimed_accounts ||= Account.where(:partner => @current_partner_name, :claimed_by_guest => false, :creator_id => '').desc(:created_at).limit(50)
      
      @total_accounts ||= @sites.count
      @total_unclaimed_accounts ||= @unclaimed_accounts.count
        
      @new_accounts_today = Site.where(:partner => current_partner.short, :created_at.gt => @date_today.at_beginning_of_day.to_time).count
      @new_accounts_week  = Site.where(:partner => current_partner.short, :created_at.gt => @date_today.at_beginning_of_week.to_time).count
      @new_accounts_month = Site.where(:partner => current_partner.short, :created_at.gt => @date_today.at_beginning_of_month.to_time).count
      @new_accounts_last_month = Site.where(:partner => current_partner.short, :created_at.gt => @date_today.at_beginning_of_month.to_time-30.days, :created_at.lt => @date_today.at_beginning_of_month.to_time).count
      @new_accounts_this_year  = Site.where(:partner => current_partner.short, :created_at.gt => Date.parse("#{@date_today.year}/1/1")).count

      @all_accounts = {}
      app_plans.each do |k,plan|
        count = Site.where(partner: current_partner.short, plan_type: plan.type).count
        @all_accounts[plan.type] = { name: plan.title + " (#{plan.frequency}ly)", count: count }
      end

    else

      @latest_sites ||= Site.desc(:created_at).limit(50)
      @unclaimed_accounts ||= Account.where(:claimed_by_guest => false, :creator_id => '').desc(:created_at).limit(50)
      
      @total_accounts ||= Site.count
      @new_accounts_today = Site.where(:created_at.gt => @date_today.at_beginning_of_day.to_time).count
      @new_accounts_week  = Site.where(:created_at.gt => @date_today.at_beginning_of_week.to_time).count
      @new_accounts_month = Site.where(:created_at.gt => @date_today.at_beginning_of_month.to_time).count
      @new_accounts_last_month = Site.where(:created_at.gt => @date_today.at_beginning_of_month.to_time-30.days, :created_at.lt => @date_today.at_beginning_of_month.to_time).count
      @new_accounts_this_year  = Site.where(:created_at.gt => Date.parse("#{Date.today.year}/1/1")).count
      @all_accounts = {}
      App.plans.each do |k,plan|
        count = Site.where(plan_type: plan.type).count
        @all_accounts[plan.type] = { name: plan.title + " (#{plan.frequency}ly)", count: count }
      end

      @num_orders = Order.not_in(status:[4,5]).count
      @today_orders = Order.where(:created_at.gt => @date_today.to_time).count
      @week_orders  = Order.where(:created_at.gt => @date_today.at_beginning_of_week.to_time).count
      @total_orders = Order.not_in(status:[4,5]).only(:total).map(&:total).compact.sum
      @today_order_totals = Order.where(:created_at.gt => @date_today.to_time).only(:total).map(&:total).compact.sum
      @week_order_totals  = Order.where(:created_at.gt => @date_today.at_beginning_of_week.to_time).only(:total).map(&:total).compact.sum
    end
    
    respond_with @latest_sites, @unclaimed_accounts

  end

end

app/views/admin/dashboard/_breadcrumbs.html.slim
li
  h1
    = @page_title
  / = link_to "Home", root_path
  / |  &raquo; 
  / = render_crumbs

app/views/admin/dashboard/_heading.html.slim
h1 Dashboard

app/views/admin/dashboard/_home.html.slim
div class="well span8"
  h3 
    = @total_sites
    | &nbsp;Latest Sites
  table class="table table-striped"
    thead
      tr
        th Partner
        th Title
        th Subdomain
        th Plan Type
        th Date Created
    tbody id="latest-sites"
      = render :partial => "admin/dashboard/latest_sites"

div class='span4'
  
  div class="well"
    - if infinitely_admin?
      = link_to "Replicate a Site", new_site_path, :class => 'btn btn-primary btn-large'
      | &nbsp;
    = link_to "Batch Create Accounts", new_multiple_accounts_path, :class => 'btn btn-primary btn-large'

  div class='well'
    h2 class="well-header"
      = number_with_delimiter(@total_accounts,:delimiter=>',')
      |  Total Sites
    h3
      = @new_accounts_today
      | <small> New Sites Today</small>
    h3
      = @new_accounts_week
      | <small> New Sites This Week</small>
    h3
      = @new_accounts_month
      | <small> New Sites This Month</small>
    h3
      = @new_accounts_last_month
      | <small> New Sites Last Month</small>
    h3
      = @new_accounts_this_year
      | <small> New Sites This Year</small>

  div class='well'
    h2 class="well-header" Accounts breakdown
    ul class="unstyled accounts-list"
      - @all_accounts.each do |k,v|
        li
          = link_to "#{number_with_delimiter(v[:count])} #{v[:name]} accounts", sites_url(plan: k)

  - if @total_orders

    div class='well'
      h2 class="well-header" Orders breakdown
      
      h3
        = number_with_precision(@total_orders,:delimiter=>",",:precision=>2)
        small  total
      
      h3
        = number_with_precision(@today_order_totals,:delimiter=>",",:precision=>2)
        small  order totals today
      
      h3
        = number_with_precision(@week_order_totals,:delimiter=>",",:precision=>2)
        small  order totals this week

      hr

      h3 
        span title='Total Number of Orders' = @num_orders
        small  orders
      
      h3
        span title='Orders today' = @today_orders
        small  orders today
      
      h3
        span title='Orders this week' = @week_orders
        small  orders this week

app/views/admin/dashboard/_latest_sites.html.slim
- @latest_sites.each do |site|

  tr id="latest-site-#{site.id}"
    td 
      small = site.partner.upcase rescue ""
    td
      = link_to site.title, site
    td
      = link_to site.subdomain, site
      | &nbsp;(
      = link_to "Visit ...", site.url, :class => "small", :target => :blank
      | )
    td
      = link_to site.plan_type, sites_url(plan: site.plan_type), :class => "plan_#{site.plan_type}"
    td
      small
        #{time_ago_in_words site.created_at} ago

app/views/admin/dashboard/_sidebar.html.slim
- if params[:controller] == 'admin/coupons'
  / h6 Search Admin

  / div class="pull-left"
  /   = render :partial => "shared/admin_search"

  / div class="pull-right"
  = render :partial => "admin/coupons/search_coupons"
- else
  /= render :partial => "shared/admin_search"
  - if params[:controller]=='admin/sites'
    div class="well sidebar-nav"
      a href=sites_url(:sort_by => @sort_by, :sort_dir => @sort_dir, :plan => @plan, :format => :csv)
        | Download as CSV ...

app/views/admin/dashboard/_unclaimed_accounts.html.slim
- @unclaimed_accounts.each do |account|
  tr id="latest-site-#{account.id}"
    td
      = link_to account.name, account
    td
      = account.ip_address.nil? ? "" : link_to(account.ip_address, account)
    td
      #{time_ago_in_words account.created_at} ago
    td

app/views/admin/dashboard/index.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = "Infinite.ly | Dashboard"
    
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    / /[if lt IE 9]
    /   = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "admin", :media => "all"
    / link href="images/favicon.ico" rel="shortcut icon"
    / link href="images/apple-touch-icon.png" rel="apple-touch-icon"
    / link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"
    / link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"


  body
    div class="container-fluid masthead"

      header id="head" class="clearfix"
        h1 class="span4"
          a class="brand" href="/" = infinitely_admin? ? "Infinitely" : "#{@partner_hash.name}"
        p class="pull-right"
          = link_to("#{@current_admin} | Logout", admin_logout_path)

      br class="clear"

      div class="navbar"
        div class="navbar-inner"
          = render :partial => "shared/admin_navigation"

    ul class="breadcrumb"
      li
        h1 Dashboard

      li class="pull-right"
        = render :partial => "shared/admin_search"
      
    div class="container-fluid row-fluid"
      = render :partial => "admin/dashboard/home"


    footer
      p &copy; Infinite.ly 2012
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "admin"