config/routes.rb
Customagic::Application.routes.draw do

  # Admin Routes
  constraints RouteConstraints::Subdomain::Admin do
    devise_for :admin, path: "", module: "admin",
      path_names: { sign_in: :login, sign_out: :logout },
      only: [:sessions, :passwords, :unlock]

    as :admin do
      get   "login"   => "admin/sessions#new",     as: :admin_login
      post  "login"   => "admin/sessions#create",  as: :admin_session
      get   "logout"  => "admin/sessions#destroy", as: :admin_logout

      resource :password, controller: "admin/passwords"
    end

    scope module: "admin" do
      resources :mastheads
      resources :shops
      resources :orders
      resources :users
      resources :products do
        get :toggle_feature
        get :toggle_visibility
        get :update_category
      end
      resources :themes
      resources :admins
    end

    match 'login_as/:user_id' => 'admin/user_sessions#create', as: :login_as
    match 'search' => 'admin/search#index'

    match "sites-validate" => "sites#validate"
    match "users-validate" => "user#validate"

    root to: "admin/dashboard#index"

  end

  resource :marketplace do
    get :featured
    get :fresh
  end
  resources :canned_images do 
    get :memes, on: :collection
  end
  resources :shops do
    get  :successful_purchase
    get  :cancelled_purchase
    resources :assets do
      post :create_photo, on: :collection
    end
    resources :customers
    resources :earnings
    resources :products do
      get  :edit_info,    on: :member
      post :update_info,  on: :member
      get  :ready,        on: :member
    end
  end

  resources :products
  
  resources :carts do
    get 'view',           on: :collection
    get 'check_out',      on: :collection
    get 'empty',          on: :collection
    get 'update_cart',    on: :collection
    get 'add_product',    on: :collection
    get 'remove_product', on: :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in',  :to => 'devise/sessions#new',     :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users

  match '/orders' => "orders#create", :method => :post
  match '/shop/successful_purchase' => 'shops#successful_purchase', :method => :get
  match '/shop/cancelled_purchase'  => 'shops#cancelled_purchase',  :method => :get
  match "/payment_notifications/paypal" => "payment_notifications#paypal", :as => :paypal_payment_notifications
  # match "/:shop_id/:id" => "products#show", :method => :get
  match "/:shop_id/products/new" => "products#new", :method => :get
  match "/:shop_id/products/:id/edit" => "products#edit", :method => :get
  match "/:shop_id/products/:id/edit_info" => "products#edit_info", :method => :get
  match "/user/hearts" => "users#hearts"
  match "/user/toggle_heart/:id" => "users#toggle_heart"
  match "/:id" => "shops#show", :method => :get

  root :to => "landing#index"

end

app/views/shared/_countdown.html.slim
javascript:
  $(function(){
    $('.product_countdown').
      each(function(){
        var el = $(this);
        el.countdown( el.attr('data-campaign-start'), function(event) {
           el.html(event.strftime(''
             + '<span>%D</span> days '
             + '<span>%H</span> hours '
             + '<span>%M</span> minutes '
             + '<span>%S</span> seconds'));
         });
      });
  });

app/views/shared/_facebook_initialization.html.slim
div id="fb-root"

javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=#{app_facebook_id}";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

- content_for :page_scripts do
  
  javascript:
    
    FACEBOOK_AUTH_URL="#{user_omniauth_authorize_path(:facebook)}";
    Hearts.initialize();

app/views/shared/_facebook_integration.html.slim
div id="fb-root"

javascript:    
  //
  // retrieve customer information if they're logged in to FB
  // enable customer review forms
  //

  SHOP_SLUG = "";

  var find_or_create_user = function(resp, callback){
      //console.log(resp);
      $.jsonp({
        url : "/users/" + resp.id + ".json?callback=?",
        type : "GET",
        dataType : 'jsonp',
        data : {  fb_id       : resp.id, 
                  email       : resp.email, 
                  name        : resp.name, 
                  first_name  : resp.first_name,
                  last_name   : resp.last_name,
                  city        : resp.location.name,
                  fb_link     : resp.link, 
                  fb_username : resp.username },
        success : function(data) {
          callback.call(this,data);
        }
      });
    }, 
    populate_address_fields = function(customer){
      //console.log(customer);
      $("#order_first_name").val( customer.first_name );
      $("#order_last_name").val( customer.last_name );
      $("#order_email").val( customer.email );
      $("#order_phone").val( customer.mobile );
      $("#order_address").val( customer.address );
      $("#order_city").val( customer.city );
      $("#order_state").val( customer.state );
      $("#order_country").val( customer.country );
      $("#order_postcode").val( customer.postcode );
    },
    create_account = function(){

      window.location.replace("/" + SHOP_SLUG + "/products/new");

    },
    replace_fb_profile = function(auth_response, callback) {
      
      FB.api('/me', function(response) {

        var cont    = $(".facebook_profile_container"),
            profile = $("<span class='fb_user_name'></span>").append("Hello, <a href='" + response.link + "' class='user_override'>" + response.name + "</a>! (<a class='fb_logout'>logout</a>)"),
            avatar  = $("<span class='fb_user_avatar'></span>").css({backgroundImage:'url(https://graph.facebook.com/' + response.id + '/picture?type=small)'}),
            button = $("<button class='start_designing'>Get Started &raquo;</button>").click(create_account);
        
        cont.empty().append(profile).append(avatar).append(button);
        
        $(".fb_logout",cont).click(function(){
          FB.logout(auth_response.authResponse);
        });

        if (callback) {
          callback.call(this,response);
        }

      });
      
    },
    enable_review_fields = function(fb_object){
      
      if (!$(".review_form").length){ return false; }

      $("textarea,input,.ratings",".review_form").removeAttr('disabled','disabled').removeClass('disabled');
      $("#product_review_fb_id").val(fb_object.id);
      $("#product_review_name").val(fb_object.name);
      $("#product_review_username").val(fb_object.username);
      $("#product_review_email").val(fb_object.email);
      $("#product_review_url").val(fb_object.link);
      $("#product_review_avatar").val("https://graph.facebook.com/" + fb_object.id + "/picture");
      
      $("#ratings .rating").
        mouseover(function(){
          var hover = $("#ratings").attr('data-hover');
          $(this).addClass('hovering').prevAll(".rating").addClass('hovering');
          $(this).html(hover).prevAll('.rating').html(hover);
          
        }).
        mouseout(function(){
          var out = $("#ratings").attr('data-out');
          $("#ratings .rating").removeClass('hovering');
          if (!$(this).hasClass('selected')) {
            $("#ratings .rating").html(out);
          }
        }).
        click(function(){
          var score = $(this).attr('data-target'),
              hover = $("#ratings").attr('data-hover'),
              out   = $("#ratings").attr('data-out');
          
          $("#product_review_rating").val(score);
          $("#ratings .rating").removeClass('selected').html(out);
          
          $(this).
            addClass('selected').
            html(hover).
            prevAll(".rating").
            addClass('selected').
            html(hover);
        });

      $(".review_form input[type=submit]").click(function(){
        
        if (!$("#product_review_rating").val().length) {
          Flasher.add(['error', "You forgot to rate the product!"], true);
          return false;
        }

        var bttn  = $(this).attr('disabled','disabled').
                      addClass('disabled').
                      val('Submitting ...');
        
        if ($("input[name=post_to_facebook]").is(":checked")) {
          var data = {
              message : $("#product_review_body").val(),
              name    : PRODUCT.name + " at " + SITE_OBJECT.title,
              picture : PRODUCT.images.length ? PRODUCT.images[0][1] : '',
              link    :  window.location.href,
              description : $(".product_description").text(),
              type    : 'link' 
            };

          FB.api('/me/feed','post', data, function(response){
            if (!response || response.error) {
              //
            } else {
              //
            }
            $(".review_form").submit();
          });

        } else {
        
          $(".review_form").submit();
        
        } 
        return false;
      });
    },
    disable_review_fields = function(fb_object) {
      if (fb_object) {
        var review_id = $(".review[data-fbid=" + fb_object.id + "]").attr('id');
        $("#reviews").addClass('existing_review');
        $(".existing_review","#reviews").find(".link_to_review").attr('href',"#" + review_id);
      }
      $("textarea,input,.ratings",".review_form").attr('disabled','disabled').addClass('disabled');
    },
    manage_review_fields = function(response) {
      if (!$(".review_form").length){ return false; }
      var ids = $(".review").map(function(){ return $(this).attr('data-fbid'); });
      if (_.include(ids,response.id)) {
        disable_review_fields(response);
      } else {
        enable_review_fields(response);
      }
    };

  // FB initialization
  window.fbAsyncInit = function() {

    FB.init({
      appId      : '#{app_facebook_id}',                        
      channelUrl : '//#{app_url.gsub('http://','')}/channel.html',  
      status     : true,                                            
      xfbml      : true                                             
    });

    FB.Event.subscribe('auth.authResponseChange', function(auth_response) { 
      if (auth_response.status === 'connected') {
        
        replace_fb_profile(auth_response, function(response){
          if (!response.email || !response.last_name) {
            FB.login(function(){},{scope:'email,user_location,publish_actions'});
          } else {
            find_or_create_user(response, function(user_shop){
              SHOP_SLUG = user_shop.slug;  
            });
            manage_review_fields(response);
          }
        });

      } else if (auth_response.status === 'not_authorized') {
        FB.login(function(){},{scope:'email,user_location,publish_actions'});
        disable_review_fields(auth_response);

      } else {
        FB.login(function(){},{scope:'email,user_location,publish_actions'});
        disable_review_fields(auth_response);

      }
    });

  };

  $(function(){

    $(".login_via_facebook").click(function(){
      FB.login(function(){},{scope:'email,user_location,publish_actions'});
    });

  });

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/shared/_header.html.slim
nav id="main" data-topbar="true" class="top-bar clearfix"
  section class="top-bar-section collapse main-nav"
    ul class="title-area nolist"
      li 
        h1 class="logo title-area" 
          a href="/" = app_name
      li
        p class="toggle-topbar menu-icon"
          a href="#"
            span Menu
    - if user_signed_in?
      ul class="navigation clearfix right nolist settings_nav"
        li class='nav_link left shopping_cart'
          - if current_user.carts.active
            a href=''
              span class='icon-cart'
              span class='shopping_cart_counter' = current_user.carts.active.quantities

        li class='nav_link left'
          a href="/marketplace" Go to marketplace »
        li class='nav_link left'
          a href="/logout" Logout

  section class="top-bar-section collapse secondary-nav"
    h2 class="hidden title" User actions
    - if is_owner?(@current_shop)
      ul class='navigation clearfix left nolist breadcrumb'
        li class='nav_link left'
          - if user_signed_in?
            h2 class="text-center" Hey there, #{current_user.first_name}!
        
        li class='nav_link left'
          a href="/#{@current_shop.slug}" 
            span class='icon-home'
            | Your Shop
        /- if @current_product
        /  li class='nav_link left'
        /    a href="/#{@current_shop.slug}/#{@current_product.slug}" = @current_product.name

        li class='management_link left'
          = link_to "<span class='icon-bars'></span>Earnings".html_safe, shop_earnings_path(@current_shop)

        li class='management_link shop_settings_link left'
          = link_to "<span class='icon-cog'></span>Settings".html_safe, edit_shop_path(@current_shop)

        li class='management_link left create_new_item'
          = link_to "<span class='icon-plus'></span>Create a New Item".html_safe, "/#{@current_shop.slug}/products/new"  


    - else
      ul class='navigation clearfix left nolist breadcrumb'
        li class='nav_link left'
          a href="/marketplace" Marketplace
        - if @current_shop
          li class='nav_link left'
            a href="/#{@current_shop.slug}" = @current_shop.name
          - if @current_product
            li class='nav_link left'
              a href="/#{@current_shop.slug}/#{@current_product.slug}" = @current_product.name
        - else
          li class='nav_link left'
            = link_to "Featured", featured_marketplace_path
          li class='nav_link left'
            = link_to "Fresh", fresh_marketplace_path
          - if user_signed_in?
            li class='management_link left'
              = link_to "Manage Your Shop", "/#{current_user.shop.slug}"  

br class="clear"

app/views/shared/_messages.html.slim
div id='messages'
  - [:notice, :alert, :error, :warning, :success].each do |key|
    - unless flash[key].blank?
      p data-alert="true" class="alert-box #{key}"
        = flash[key] 
        a href="#" class="close" 
          | &times;

- content_for :page_scripts do  
  javascript:
    $(function(){
      Flasher.initialize();
    });