config/routes.rb
Customagic::Application.routes.draw do

  # Admin Routes
  constraints RouteConstraints::Subdomain::Admin do
    devise_for :admin, path: "", module: "admin",
      path_names: { sign_in: :login, sign_out: :logout },
      only: [:sessions, :passwords, :unlock]

    as :admin do
      get   "login"   => "admin/sessions#new",     as: :admin_login
      post  "login"   => "admin/sessions#create",  as: :admin_session
      get   "logout"  => "admin/sessions#destroy", as: :admin_logout

      resource :password, controller: "admin/passwords"
    end

    scope module: "admin" do
      resources :mastheads
      resources :shops
      resources :orders
      resources :users
      resources :products do
        get :toggle_feature
        get :toggle_visibility
        get :update_category
      end
      resources :themes
      resources :admins
    end

    match 'login_as/:user_id' => 'admin/user_sessions#create', as: :login_as
    match 'search' => 'admin/search#index'

    match "sites-validate" => "sites#validate"
    match "users-validate" => "user#validate"

    root to: "admin/dashboard#index"

  end

  resource :marketplace do
    get :featured
    get :fresh
  end
  resources :canned_images do 
    get :memes, on: :collection
  end
  resources :shops do
    get  :successful_purchase
    get  :cancelled_purchase
    resources :assets do
      post :create_photo, on: :collection
    end
    resources :customers
    resources :earnings
    resources :products do
      get  :edit_info,    on: :member
      post :update_info,  on: :member
      get  :ready,        on: :member
    end
  end

  resources :products
  
  resources :carts do
    get 'view',           on: :collection
    get 'check_out',      on: :collection
    get 'empty',          on: :collection
    get 'update_cart',    on: :collection
    get 'add_product',    on: :collection
    get 'remove_product', on: :collection
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in',  :to => 'devise/sessions#new',     :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users

  match '/orders' => "orders#create", :method => :post
  match '/shop/successful_purchase' => 'shops#successful_purchase', :method => :get
  match '/shop/cancelled_purchase'  => 'shops#cancelled_purchase',  :method => :get
  match "/payment_notifications/paypal" => "payment_notifications#paypal", :as => :paypal_payment_notifications
  # match "/:shop_id/:id" => "products#show", :method => :get
  match "/:shop_id/products/new" => "products#new", :method => :get
  match "/:shop_id/products/:id/edit" => "products#edit", :method => :get
  match "/:shop_id/products/:id/edit_info" => "products#edit_info", :method => :get
  match "/user/hearts" => "users#hearts"
  match "/user/toggle_heart/:id" => "users#toggle_heart"
  match "/:id" => "shops#show", :method => :get

  root :to => "landing#index"

end

app/models/product/characteristics.rb
class Product
  module Characteristics
    extend ActiveSupport::Concern

    included do
      
      field :product_type,         default: "shirt" 
      field :product_style,        default: "basic"
      field :product_sub_style,    default: "basic_standard"
      field :color,                type: String,   default: "#ffffff"
      field :final_art_dimensions, type: Array, default: [0,0]
      field :mockup_dimensions,    type: Array, default: [0,0]
      #before_save :set_pricing
    end

    def remaining
      sales_goal-num_orders
    end

    def product_type_object
      App.product_types.find{|pt|pt.slug==product_type}
    end

    def product_style_object
      product_type_object.product_styles.find{|ps| ps.slug==product_style}
    end

    def product_sub_style_object
      product_style_object.sub_styles.find{|pss| pss.slug==product_sub_style}
    end

    def base_price
      product_sub_style_object.highest_production_price
    end
    
    def update_sales_information!
      self.base_price = product_sub_style_object.highest_production_price
      hash = []
      product_style_object.sizes.each do |psize|
        hash << { primary: psize, secondary: "", quantity: 1000000, price: buy_now_price }
      end
      self.price_variants = hash
      self.save
    end

    def production_price_steps
      (product_sub_style_object.highest_production_price-product_sub_style_object.lowest_production_price)/product_sub_style_object.delta
    end

    def production_cost
      hp  = product_sub_style_object.highest_production_price
      lp  = product_sub_style_object.lowest_production_price
      del = product_sub_style_object.delta

      [hp-(num_orders*del),lp].max
    end

  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  include ApplicationHelper
  #include SitesHelper
  before_filter :set_product, :only => [ :toggle_feature, :toggle_visibility, :update_category ]

  # add_crumb("Products") { |instance| instance.send :products_path }

  respond_to :js, :html, :json

  def index
    @page_title = "Products"
    @only = 'products'
    if is_infinitely_admin?
      @products_count = Product.where(:status.ne => 9).count
      @featured_products_count = Product.where(:featured_in_marketplace => true).count
      @products = Product.where(:status.ne => 9) #.desc(:created_at)
    elsif current_partner.has_marketplace?
      @products_count = Product.where(:status.ne => 9, :partner=>current_partner.short).count
      @featured_products_count = Product.where(:featured_in_marketplace => true, :partner=>current_partner.short).count
      @products = Product.where(:status.ne => 9, :partner=>current_partner.short) #.desc(:created_at)
    end

    sort_by = params[:sort_by] ||= :created_at
    sort_dir = params[:sort_dir] ||= :desc

    if params[:sort_by]
      @products = @products.order_by([sort_by.to_sym, sort_dir.to_sym])
    else
      @products = @products.order_by([:created_at, :desc])
    end

    @products = @products.page(params[:page]).per(params[:per]||100) #Kaminari.paginate_array(@products).page(params[:page]).per(params[:per] || 100)
    respond_with @products
  end

  def toggle_feature
    @product.toggle!(:featured_in_marketplace)
    respond_with @product
  end

  def toggle_visibility
    @product.toggle!(:visible_in_marketplace)
    respond_with @product
  end

  def update_category
    @product.category_slug = params[:product][:category_slug]
    @product.save(:validate=>false)
    respond_with @product.reload
  end

  protected

    def set_product
      @product = Product.find(params[:product_id])
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  include ApplicationHelper

  before_filter :set_shop

  before_filter :set_product, only: [ :edit, :edit_info, :update, :update_info, :ready, :destroy, :show ]
  before_filter :authenticate_user!, except: [ :show ]
  before_filter :authorize_account_user!

  before_filter :check_product_visibility, only: [ :show ]

  respond_to :html, :json

  def index

  end

  def show

  end

  def new
    if @product = @current_shop.products.create(name: "Awesome Shirt")
      redirect_to "/#{@current_shop.slug}/products/#{@product.slug}/edit"
    else
      flash[:alert] = "We couldn't add a new product to your shop."
      redirect_to "/#{@current_shop.slug}"
    end
  end

  def create

  end

  def edit
    @assets = @product.assets
    @images = @shop.images
    render :layout => "editor"
  end

  def edit_info
    render :layout => "editor"
  end

  def ready
    render :layout => "editor"
  end

  def update
    if @product.update_attributes(params[:product])
      @product.generate_art!
      respond_to do |format|
        format.json { render :json => @product }
      end
    end
  end

  def update_info
    if @product.update_attributes(params[:product])
      @product.update_sales_information!
      respond_to do |format|
        format.html { redirect_to :action => :ready }
      end
    else
      respond_to do |format|
        format.html do
          flash[:alert] = "Your product information couldn't be saved!"
          render :layout => "editor", :action => :edit_info
        end
      end
    end
  end

  def make_ready
    @product.update_attributes(status: 2)
    respond_to do |format|
      flash[:notice] = "Your work is now visible in the marketplace!"
      redirect_to product_path(@product)
    end
  end

  def destroy
    @product.destroy
    @product.assets.destroy_all
    respond_to do |format|
      format.json { render :inline => { :success => true } }
    end
  end

  protected
    def set_shop
      @current_shop = Shop.find(params[:shop_id]) if params[:shop_id]
    end

    def set_product
      unless @product = Product.find(params[:id])
        flash[:alert] = "We couldn't find that item."
        redirect_to "/#{@current_shop.slug}"
      end
      @current_product = @product
      @current_shop ||= @product.shop
      @shop = @current_shop
    end

    def check_product_visibility
      if @product.status<=1 && !is_owner?(@current_shop)
        flash[:alert] = "This product isn't available yet."
        redirect_to "/#{@current_shop.slug}"
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def countdown(product)
    if product.availability_start && Time.now < product.availability_start+product.campaign_length.days
      t_then = product.availability_start + product.campaign_length.days
      t_now = Time.now
      return Time.diff(t_then, t_now, "<span>%d</span> days <span>%h</span> hours <span>%m</span> mins <span>%s</span> secs")[:diff] + " left"
    else
      return 0
    end
  end
end

app/views/products/_product.html.slim
li class='product'
  
  h3 class='product_name' 
    = link_to product.name, shop_product_path(@current_shop, product)

  - if product.final_art
    div data-turbolinks-track='true' class='product_image' style='background-color: #{product.color}; background-image:url(#{product.final_art.attachment.medium.url})' = link_to "", shop_product_path(@current_shop, product)
  - else
    div class='product_image dummy_product_image' = link_to "", shop_product_path(@current_shop, product)

  div class='product_prices product_info'
    ul class="nolist clearfix"
      li class='buy_now_price left'
        p 
          | #{link_to(number_to_currency(product.buy_now_price, unit: @current_shop.currency_symbol), shop_product_path(@current_shop, product))}
      li class='donation right'
        - if product.charity_donation > 0 && product.charity
          p
            = number_to_currency(product.charity_donation, unit: @current_shop.currency_symbol)
            |  of each #{product.product_type} sold will be donated to 
            = link_to product.charity.name, product.charity.url

  div class='product_hearts product_info'
    span class='icon heart toggle_heart' data-id=product.id <3
    - if product.num_favorites>0
      span class='heart_counter' 0
  
  - if product.has_charity?
    div class='product_charity'
      span class='icon charity #{product.charity.slug}' 
        = product.charity.name
        
  - if is_owner?(@current_shop)
    p class="product_info"
      - if product.is_orderable?
        = link_to "Edit Pricing &raquo;".html_safe, edit_info_shop_product_path(@current_shop, product)
      - else
        = link_to "Edit Design &amp; Pricing &raquo;".html_safe, edit_shop_product_path(@current_shop, product)

app/views/products/_steps.html.slim
nav class='steps small-12 medium-12 clearfix'
  h2 class="steps_title small-12 medium-12 large-3 left" Create a New Item
  ol class="clearfix small-12 medium-12 large-9 left"
    li class='step active' data-target='step_1' 
      a href="/#{@current_shop.slug}/products/#{@product.slug}/edit" 
        span class='button button-icon'
          span
            span
              | 1
        | Design Your #{@product.product_type.titleize}
    li class='step next_step' data-target='step_2' 
      a href="/#{@current_shop.slug}/products/#{@product.slug}/edit_info" class="next_step"
        span class='button button-icon inactive'
          span
            span
              | 2

        | Set Pricing
    li class='step last_step' data-target='step_3'
      a href="/shops/#{@current_shop.slug}/edit" class="next_step"
        span class='button button-icon inactive'
          span
            span
              | 3
        | Launch!

app/views/products/edit_info.html.slim
div id='editor' class='information small-12 small-uncentered medium-12 medium-centered row'
  
  = render :partial => "products/steps"

  div class='inner clearfix'
    div class='viewer columns medium-4 small-12'

      div class='item' style='background-color: #{@product.color}; background-image: url(#{@product.art_attachment.medium.url})'

      div class='item_specifications'

        dl
          dt 
            strong #{@product.product_type_object.name} Style
          dd = "#{@product.product_style_object.name} (#{@product.product_sub_style_object.name})"
          dt 
            strong #{@product.product_type_object.name} Color
          dd 
            = "#{@product.color}"
            span class='color_swatch' style='background-color:#{@product.color}'
          dt
            strong Download Print-Ready Image
          dd
            = link_to truncate(@product.art_attachment.url, length:50), @product.art_attachment.url, target: "_blank"

    div class='info_form_container columns medium-4 small-12'

      = simple_form_for @product, :url => update_info_shop_product_path(@current_shop, @product), :method => :post do |f|

        = f.input :name

        = f.input :description, :as => :text

        dl class='production_cost'
          dt data-hint="Your first shirt will cost this much to produce" class="hint--right" 
            label Production Cost
          dd            
            h3 data-float=@product.product_sub_style_object.production_price class='production_cost currency' 
              = @product.product_sub_style_object.production_price


        = f.input :buy_now_price, label: "Retail Price (#{@current_shop.currency_symbol})", input_html: { class: 'currency' }

        = f.input :charity_donation, label: "Donation (#{@current_shop.currency_symbol})", \
          input_html: { class: 'currency hint--bottom', "data-hint".to_sym => "You may optionally donate a portion of your profit to charity"  }
        
        = f.input :charity_url, collection: App.charities.map{|c| [c.name, c.url]}, label: "Charity", include_blank: false

        div class="submit_button"

          span class="button active"
            span
              = f.submit "Save and Proceed", "class" => "button_inner_most"
              //== f.submit "Save and Proceed", { 'data-hint'.to_sym => "Next step: Final Check" }, "class" => "button_inner_most"

          button class='delete_product destroy_button button warning'
            span
              span class="button_inner_most" Delete This Item

    div class='totals_and_instructions columns medium-4 small-12'

      dl class='totals'
        dt Your Current Sales
        dd = @product.num_orders
        dt Your Earnings After Your First Sale
        dd 
          span class='total_earnings_1 currency' 0
        dt Your Earnings at 20 Units
        dd data-hint="You'll earn this much if you sell 20" class="hint--left"
          span class='total_earnings_20 currency' 0
        dt Your Earnings at 100 Units
        dd data-hint="You'll earn this much if you sell 100" class="hint--left"
          span class='total_earnings_100 currency' 0

      div class='help'
        dl class='faq'
          dt
            h3 How does this work?
          dd
            p
              | Just add a name and description for your #{@product.product_type}, set your retail price, and you're good to go! Once your #{@product.product_type} has received at least #{@product.product_sub_style_object.minimum_favorites} hearts, we'll begin immediate production. We'll keep you updated regarding your sales via your Earnings page.
          dt 
            h3 Am I required to give a portion of my profit to a charity?
          dd
            p 
              | No, but it's a nice thing to do. Note that your product's page will indicate which charity you have chosen to support.
          dt
            h3 How will I get paid?
          dd
            p
              | Every 30 days where your earnings exceed PhP2,000.00, we'll send money to a Paypal account or local bank account of your choosing. If your earnings are less than PhP2,000.00 at the end of a 30-day cycle, we'll hold it and wait for the next cycle.
          

- content_for :page_scripts do
  
  javascript:
    var SHOP = #{@current_shop.to_json.html_safe},
        TYPES = #{App.product_types.to_json.html_safe},
        PRODUCT = #{@product.to_json(methods: [:slug]).html_safe};

    $(function(){
      Calculator.initialize(SHOP, TYPES, PRODUCT);

      $(".delete_product").click(function(){
        var bttn = $(this);
        if (confirm("Are you sure you want to delete this item?")) {
          bttn.text("Deleting ...");
          $.ajax({
            url : "/shops/" + SHOP.slug + "/products/" + PRODUCT.slug,
            type : "DELETE",
            success : function(data) {
              Flasher.add(['notice',"You've deleted this item successfully. Redirecting you to your shop ..."]);
              window.location.assign="/" + SHOP.slug;
            }
          })
        }
      });
    });

app/views/products/ready.html.slim
div id='editor' class='information small-12 small-uncentered medium-12 medium-centered row'
  
  = render :partial => "products/steps"

  div class='inner clearfix'
    div class='viewer columns medium-5 small-12'

      div class='item' style='background-color: #{@product.color}; background-image: url(#{@product.art_attachment.medium.url})'

      div class='item_specifications'

        dl
          dt 
            strong #{@product.product_type_object.name} Style
          dd = "#{@product.product_style_object.name} (#{@product.product_sub_style_object.name})"
          dt 
            strong #{@product.product_type_object.name} Color
          dd 
            = "#{@product.color}"
            span class='color_swatch' style='background-color:#{@product.color}'
          dt
            strong Download Print-Ready Image
          dd
            = link_to truncate(@product.art_attachment.url, length:50), @product.art_attachment.url, target: "_blank"

    div class='info_form_container columns medium-7 small-12'

      h1 Final Check 

      p 
        | Click the button below to start displaying your #{@product.product_type} within the marketplace. Note that it won't immediately go on sale. Each design requires a minimum of #{@product.product_sub_style_object.minimum_favorites} hearts before we can start producing it.

      p 
        | Once your design has received #{@product.product_sub_style_object.minimum_favorites} hearts, we will notify you and production will begin. Your shirts will typically be available for sale within 5-10 days.

      = simple_form_for @product do |f|

        = f.input :status, :as => :hidden, :value => 2

        div class="submit_button"
          span class="button active"
            span
              = f.submit "Ready!", :class => "button_inner_most"

        = link_to "I want to work on my design some more ...", edit_product_path(@current_shop, @product)


            

app/views/products/show.html.slim
- @page_title = "#{@product.name} | #{@current_shop.name}"
div class='product standalone_product small-12 small-uncentered medium-centered row'

  div class='medium-7 small-12 columns'

    div class=" product_image_container product_image_container_#{@product.product_type} #{@product.product_type}_#{@product.color.gsub('#','')}"
      div data-turbolinks-track='true' class='product_image' style='background-image:url(#{@product.art_attachment.medium.url})'
      
    div class='product_description'

      == @product.description

    div class='product_share_tools small-12'
      div class='share_facebook small-12 medium-3 columns'
        iframe src="//www.facebook.com/plugins/like.php?href=#{shop_product_url(@shop.slug, @product.slug)}&height=65&colorscheme=light&layout=box_count&action=like&show_faces=true&send=false&appId=#{app_facebook_id}" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:65px;" allowTransparency="true"
      div class='share_gplus small-12 medium-3 columns'              
        div class="g-plusone" data-size="tall" data-width="50"
        javascript:
          (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
          })();
      div class='share_twitter small-12 medium-3 columns'
        iframe allowtransparency="true" frameborder="0" scrolling="no" src="https://platform.twitter.com/widgets/tweet_button.html?related=socialinfinity&url=#{shop_product_url(@shop.slug, @product.slug)}&text=#{@product.name}+#{@product.price}&count=vertical" class="twitter-share-button" style="width:60px;"
      div class='share_pinterest small-12 medium-3 columns'
        div style="margin-top:10px;"
          a target="_blank" href="//pinterest.com/pin/create/button/?url=#{CGI.escape(shop_product_url(@shop.slug, @product.slug))}&media=#{@product.primary_image}&description=#{CGI.escape(@product.name)}+#{@product.price}" data-pin-do="buttonPin" data-pin-config="above" always-show-count="true"
            img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" 

  div class='product_purchase columns small-12 medium-5'

    div class='inner'
      header class="product_header"
        h1 
          = @product.name
          | &nbsp;
        p class='byline' 
          | by 
          span class='author_name' 
            = link_to @current_shop.user.name, ""
          - if is_owner?(@current_shop)
            span class='owner_tools'
              = link_to "Edit &raquo;".html_safe, edit_info_shop_product_path(@current_shop, @product)

      div class='product_prices'

        h3 class='unit_price currency' = number_to_currency(@product.buy_now_price, unit: @current_shop.currency_symbol)
        
        - if @product.is_orderable?

          = link_to "Add to Cart", add_product_carts_path(product_id: @product.id), class: 'buy_now', "data-loading".to_sym => "Adding ..." 

      div class='product_hearts product_info button active'
        span
          span class='icon button_inner_most heart toggle_heart' data-id=@product.id
            = @product.num_favorites
          
      - if @product.is_pending?
        hr class="divider"
        div class='product_pending'
          p This #{@product.product_type} is not yet available for ordering. It needs #{pluralize @product.favorites_remaining,'heart'} in order for us to start production. If you want to be able to buy this #{@product.product_type}, click the Heart above and tell your friends to do the same.

      - elsif @product.is_orderable?

        hr class="divider"
        div class='product_variants'
          h4 Available Sizes
          select id='product_variant' name='product_variant'
            option value='small' Small
            option value='medium' Medium
            option value='large' Large
            option value='XL' X-Large
            option value='XXL' XX-Large

      - if @product.has_charity?

        hr class="divider"
        div class='product_donation'
          p
            = number_to_currency(@product.charity_donation, unit: @current_shop.currency_symbol)
            |  of each #{@product.product_type} sold will be donated to 
            = link_to @product.charity.name, @product.charity.url

      hr class="divider"
      div class='item_specifications'
        h4 Specifications
        dl
          dt 
            strong #{@product.product_type_object.name} Style
          dd = "#{@product.product_style_object.name} (#{@product.product_sub_style_object.name})"
          dt 
            strong Color
          dd 
            = "#{@product.color}"
            span class='color_swatch' style='background-color:#{@product.color}'

  - content_for :page_scripts do
    
    javascript:
      var SHOP    = #{@current_shop.to_json.html_safe},
          TYPES   = #{App.product_types.to_json.html_safe},
          PRODUCT = #{@product.to_json(methods: [:slug]).html_safe};

      (function(d){
        var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
        p.type = 'text/javascript';
        p.async = true;
        p.src = '//assets.pinterest.com/js/pinit.js';
        f.parentNode.insertBefore(p, f);
      }(document));

      $(function(){

        $(".buy_now").click(function(){
          var el  = $(this),
              url = $(this).attr('href') + "&product_variant=" + $("#product_variant").val();
          el.text( el.attr('data-loading') );
          window.location.assign(url);
        });

        Hearts.initialize();

      });